# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]

[plugins.defer]
github = "romkatv/zsh-defer"

[plugins.local]
local = "~/.local/bin"
apply = ["PATH"]

[plugins.wsl]
local = "/mnt/c/wsl/ubuntu/bin"
apply = ["PATH"]

[plugins.rust]
inline = 'source ~/.cargo/env'

[plugins.pnpm]
inline = '''
export PNPM_HOME="/home/alliana/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
'''

[plugins.alias]
inline = '''
alias ls="eza --icons --git"
alias ls="eza -a --icons --git"
alias cat="bat"
alias grep="rg"
alias fzf="sk"
'''

[plugins.func]
inline = '''
function ghq-fzf() {
  local src=$(ghq list | fzf --preview "bat --color=always --style=header,grid --line-range :80 $(ghq root)/{}/README.*")
  if [ -n "$src" ]; then
    BUFFER="cd $(ghq root)/$src"
    zle accept-line
  fi
  zle -R -c
}
zle -N ghq-fzf
bindkey '^]' ghq-fzf
'''

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.mise]
inline = 'eval "$(mise activate zsh)"'

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]
