[tools]
node = "22.11.0"
deno = "2.0.6"
bun = "1.1.34"
go = "1.23.3"
java = "openjdk-21"
coursier = "latest"
usage = "latest"
python = ["3.12.0", "3.11.10"]
gleam = "1.5.1"
ghc = "9.8.2"
"npm:@devcontainers/cli" = "0.72.0"
"npm:@biomejs/biome" = "1.9.4"
"npm:atcoder-cli" = "2.2.0"

[settings]
python_compile = false
experimental = true
