[tools]
node = "22.10.0"
deno = "2.0.3"
bun = "1.1.31"
go = "1.23.2"
java = "openjdk-21"
coursier = "latest"
usage = "latest"
python = "3.12.0"
gleam = "1.5.1"
ghc = "9.10.1"

[settings]
python_compile = false

